### ISSUE TITLE
Latest database dump

### ISSUE THREAD

**Issue by jcp** [amprog/teachstrong.org#4]
Can we get a database dump for the site? We have some new feature requests, which will be covered by support hours, and they'll need database modifications.

**Comment by jcp** [comment]
@bribroder bumping this.

**Comment by bribroder** [comment]
Hey James, I should be able to get you a dump this afternoon--thanks for your patience

**Comment by bribroder** [comment]
https://docs.google.com/uc?id=0B6tGD8EOO-KjRDllWDBZU0drRFE&export=download

let me know if you have any issues

**Comment by jcp** [comment]
Thanks
